
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */
public class addcategories extends javax.swing.JFrame {
File f;
    /**
     * Creates new form addcategories
     */
    public addcategories() {

       
        initComponents();
        setSize(600, 600);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        BT1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHINESE", "INDIAN", "SEAFOOD", "FRENCH", " " }));
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(120, 60, 150, 30);

        jLabel1.setText("ADD CATEGORIES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 150, 20);

        jLabel2.setText("DESCRIPTION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 160, 90, 14);

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(120, 110, 150, 30);

        jLabel3.setText("PHOTO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 280, 90, 14);

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 150, 166, 96);

        jLabel4.setText("CATEGORY");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 120, 90, 14);

        jButton1.setText("BROWSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 270, 120, 23);

        jLabel5.setText("CUISINE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 70, 90, 14);
        getContentPane().add(lb1);
        lb1.setBounds(310, 220, 90, 100);

        BT1.setText("ADD CATEGORY");
        BT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT1ActionPerformed(evt);
            }
        });
        getContentPane().add(BT1);
        BT1.setBounds(130, 340, 120, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged

    }//GEN-LAST:event_cb1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
  JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg","jgeg","bmp");//check for images onlyy
         jfc.setFileFilter(filter);
        int showOpenDialogResult = jfc.showOpenDialog(this);
        if(JFileChooser.APPROVE_OPTION == showOpenDialogResult)
        {
             f=jfc.getSelectedFile();
            BufferedImage bi = null;
      try 
      {
        
         bi = ImageIO.read(f);
             
        
      } 
      
      catch (IOException ex) 
      {
          Logger.getLogger(addcategories.class.getName()).log(Level.SEVERE, null, ex);
      } 
     
            
            lb1.setIcon(new ImageIcon(resize(bi, lb1.getWidth(), lb1.getHeight())));
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT1ActionPerformed
        // TODO add your handling code here:

      
        String c, cg, dsc, pic;

        c = cb1.getSelectedItem().toString();
        cg = tf1.getText();
        dsc = ta1.getText();
        

        if (c.equals("") || cg.equals("") || dsc.equals("")||f==null) 
        {
            JOptionPane.showMessageDialog(this, "ALL FIELDS ARE MANDATORY");

        }
        else
        {
     try
        {
            HttpResponse<String> res =  Unirest.post("http://127.0.0.1:8888/addcategories")
                                               .queryString("cuisine",c)
                                               .queryString("categories",cg)
                                               .queryString("description",dsc) 
                                               .field("photo", f)
                                               .asString();
            String response = res.getBody();
            if(response.equals("duplicate"))
            {
                  JOptionPane.showMessageDialog(this, "duplicate category name");
            }
            else
            {
              JOptionPane.showMessageDialog(this, "category added");

            }
        }
        catch (UnirestException ex)
        {
          ex.printStackTrace();
        }
       
        }
    }//GEN-LAST:event_BT1ActionPerformed

    BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addcategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addcategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addcategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addcategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addcategories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT1;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
