
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */
public class addfooditems extends javax.swing.JFrame {

    File f;

    String ftp;

    /**
     * Creates new form addfooditems
     */
    public addfooditems() {
        initComponents();
        setSize(700, 600);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cbcuisine = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbcategory = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tfprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfdesc = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        tfitemname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cbcuisine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select cuisine--", "INDIAN", "FRENCH", "CHINESE", "SEAFOOD" }));
        cbcuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcuisineActionPerformed(evt);
            }
        });
        getContentPane().add(cbcuisine);
        cbcuisine.setBounds(161, 86, 160, 30);

        jLabel1.setText("PRICE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 420, 120, 40);

        jLabel2.setText("ADD FOOD ITEMS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 30, 180, 14);

        cbcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cbcategory);
        cbcategory.setBounds(160, 150, 160, 30);

        jLabel3.setText("CUISINE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 80, 120, 40);
        getContentPane().add(tfprice);
        tfprice.setBounds(160, 420, 170, 30);

        jLabel4.setText("FOOD CATEGORIES");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 150, 120, 40);

        tfdesc.setColumns(20);
        tfdesc.setRows(5);
        jScrollPane1.setViewportView(tfdesc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 260, 166, 96);

        jLabel5.setText("ITEM NAME");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 200, 120, 40);

        buttonGroup1.add(r1);
        r1.setSelected(true);
        r1.setText("VEG");
        r1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                r1ItemStateChanged(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(160, 390, 70, 23);

        buttonGroup1.add(r2);
        r2.setText("NON VEG");
        getContentPane().add(r2);
        r2.setBounds(300, 390, 110, 23);

        jLabel6.setText("DESCRIPTION");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 280, 120, 40);
        getContentPane().add(tfitemname);
        tfitemname.setBounds(160, 210, 170, 30);

        jLabel7.setText("FOOD TYPE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 380, 120, 40);
        getContentPane().add(lb1);
        lb1.setBounds(440, 390, 170, 110);

        jButton1.setText("BROWSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 460, 120, 23);

        jButton2.setText("ADD ITEM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 490, 190, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jgeg", "bmp");//check for images onlyy
        jfc.setFileFilter(filter);
        int showOpenDialogResult = jfc.showOpenDialog(this);
        if (JFileChooser.APPROVE_OPTION == showOpenDialogResult) {
            f = jfc.getSelectedFile();
            BufferedImage bi = null;
            try {

                bi = ImageIO.read(f);

            } catch (IOException ex) {
                Logger.getLogger(addcategories.class.getName()).log(Level.SEVERE, null, ex);
            }

            lb1.setIcon(new ImageIcon(resize(bi, lb1.getWidth(), lb1.getHeight())));

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String c, in, dsc, cost, fc;
//
        c = cbcuisine.getSelectedItem().toString();
        fc = cbcategory.getSelectedItem().toString();
        in = tfitemname.getText();
        dsc = tfdesc.getText();
        cost = tfprice.getText();
        String type = r1.isSelected() ? "Veg" : "Non-Veg";
        if (c.equals("") || in.equals("") || dsc.equals("") || f == null || cost.equals("") ) {
            JOptionPane.showMessageDialog(this, "ALL FIELDS ARE MANDATORY");

        } else {
            try {
                HttpResponse<String> res = Unirest.post("http://127.0.0.1:8888/addfooditems")
                        .queryString("cuisine", c)
                        .queryString("foodcategory", fc)
                        .queryString("itemname", in)
                        .queryString("description", dsc)
                        .queryString("price", cost)
                        .queryString("foodtype", type)
                        .field("photo", f)
                        .asString();
                String response = res.getBody();
                if (response.equals("success")) {
                    JOptionPane.showMessageDialog(this, "food items added");
                } else {
                    JOptionPane.showMessageDialog(this, "not added");
                }
            } catch (UnirestException ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void r1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_r1ItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_r1ItemStateChanged

    private void cbcuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcuisineActionPerformed
        try {
            // TODO add your handling code here:
            String combo = cbcuisine.getSelectedItem().toString();
            if (cbcuisine.getSelectedIndex() >= 1) {
                HttpResponse<String> res = Unirest.get("http://127.0.0.1:8888/getcategories")
                        .queryString("cuisine", combo)
                        .asString();
                String response = res.getBody();
                StringTokenizer st = new StringTokenizer(response, "#$%");
                int n = st.countTokens();
                cbcategory.removeAllItems();
                for (int i = 1; i <= n; i++) {
                    String row = st.nextToken();
                    cbcategory.addItem(row);
                }
            }
        } catch (UnirestException ex) {
            Logger.getLogger(addfooditems.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_cbcuisineActionPerformed

    private void cbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcategoryActionPerformed
    BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addfooditems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addfooditems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addfooditems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addfooditems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addfooditems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbcategory;
    private javax.swing.JComboBox<String> cbcuisine;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextArea tfdesc;
    private javax.swing.JTextField tfitemname;
    private javax.swing.JTextField tfprice;
    // End of variables declaration//GEN-END:variables
}
