
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */
public class signup2 extends javax.swing.JFrame {

    String mobilenumber;
    String name, email, address;
    boolean flag = true;

    /**
     * Creates new form signup2
     *
     * @param mobileno
     */
    private signup2() {
        initComponents();

    }

    public signup2(String mobileno) {
        initComponents();
        publicloaddata();
        setSize(600, 600);
        setVisible(true);
        mobilenumber = mobileno;
        lbmobileno.setText(mobilenumber);
        publicloaddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbmobileno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        tfname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taaddress = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btsubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(lbmobileno);
        lbmobileno.setBounds(130, 40, 200, 30);

        jLabel2.setText("ADDRESS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 240, 120, 30);

        jLabel3.setText("MOBILE NUMBER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 40, 120, 30);

        tfemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfemailActionPerformed(evt);
            }
        });
        getContentPane().add(tfemail);
        tfemail.setBounds(120, 160, 140, 30);

        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfname);
        tfname.setBounds(120, 90, 140, 30);

        taaddress.setColumns(20);
        taaddress.setRows(5);
        jScrollPane1.setViewportView(taaddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 200, 166, 96);

        jLabel4.setText("NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 90, 120, 30);

        jLabel5.setText("EMAIL ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 160, 120, 30);

        btsubmit.setText("SUBMIT");
        btsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btsubmit);
        btsubmit.setBounds(130, 320, 120, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfemailActionPerformed

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    private void btsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsubmitActionPerformed
        name = tfname.getText();
        email = tfemail.getText();
        address = taaddress.getText();
        if (name.equals("") || email.equals("") || address.equals("")) {
            JOptionPane.showMessageDialog(this, "all fields are mandatory");

        } else {
            try {
                HttpResponse<String> res = Unirest.get("http://127.0.0.1:8888/customersignup")
                        .queryString("mobilenumber", mobilenumber)
                        .queryString("name", name)
                        .queryString("email", email)
                        .queryString("address", address)
                        .queryString("flag", flag)
                        .asString();

                String response = res.getBody();
                if (response.equals("success")) {
                    JOptionPane.showMessageDialog(this, "signup process successful");

                } else {
                    JOptionPane.showMessageDialog(this, "signup process failed");
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_btsubmitActionPerformed

    void publicloaddata() {
        try {
            mobilenumber = lbmobileno.getText();
            HttpResponse<String> res = Unirest.get("http://localhost:8888/getcustomerdetails")
                    .queryString("mobilenumber", mobilenumber).asString();
            String response = res.getBody();
            System.out.println("response " + response);
                    
                  
            if (response.equals("failed") == false) {
                flag = true;
                
                StringTokenizer st = new StringTokenizer(response, "~~~");
                System.out.println(st.countTokens());
                name = st.nextToken();
                email = st.nextToken();
                address = st.nextToken();
                tfname.setText(name);
                tfemail.setText(email);
                taaddress.setText(address);
            }
        } catch (UnirestException ex) {
            Logger.getLogger(signup2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btsubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbmobileno;
    private javax.swing.JTextArea taaddress;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfname;
    // End of variables declaration//GEN-END:variables
}
